import {apiFetch} from './api';
import {useEffect,useState,useCallback} from 'react';
import {Check,Search,Shirt,RefreshCw,Undo2,ClipboardCheck,X,PackageCheck,Clock3,ClipboardList,RotateCcw} from 'lucide-react';
type Order={id:number;name:string;quantity:number;sizes:string;verified:boolean;deliveredAt:string|null;revision:number};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export default function Home(){
 const [orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Order|null>(null),[notice,setNotice]=useState(''),[resetOpen,setResetOpen]=useState(false);
 const load=useCallback(async()=>{try{const r=await apiFetch('/api/orders',{cache:'no-store'});const d=await r.json() as {orders:Order[];error:string};if(!r.ok)throw Error(d.error);setOrders(d.orders);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),20000);return()=>clearInterval(t);},[load]);
 async function save(o:Order,action:string){setBusy(true);setError('');try{const r=await apiFetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,revision:o.revision,action})});const d=await r.json() as {orders:Order[];error:string};if(!r.ok)throw Error(d.error);setSelected(null);setNotice(action==='deliver'?'Entrega guardada correctamente.':action==='verify'?'Pedido verificado.':'La entrega se volvió a marcar como pendiente.');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function resetDeliveries(){
  setBusy(true);setError('');
  try{
   const r=await apiFetch('/api/orders/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:'reset-deliveries'})});
   const d=await r.json() as {error?:string;resetCount?:number};
   if(!r.ok)throw Error(d.error||'No se pudieron reiniciar las entregas.');
   setResetOpen(false);setFilter('all');setNotice('Entregas reiniciadas a 0. Todos los pedidos vuelven a estar por entregar.');await load();
  }catch(e){setError(e instanceof Error?e.message:'No se pudo reiniciar.');}finally{setBusy(false);}
 }
 const done=orders.filter(o=>o.deliveredAt),unverified=orders.filter(o=>!o.verified);
 const visible=orders.filter(o=>(normalize(o.name+' '+o.id).includes(normalize(query)))&&(filter==='all'||filter==='pending'&&!o.deliveredAt||filter==='done'&&o.deliveredAt||filter==='verify'&&!o.verified));
 return <><header><div className="brand"><span className="brandmark"><Shirt size={24}/></span><div><strong>COPA INTEGRACIÓN <span>2026</span></strong><small>DIRECCIÓN NACIONAL DE BOMBEROS</small></div></div><span className="headlabel">CAMISETAS / ENTREGA</span></header><main>
 <div className="intro"><div><p className="eyebrow">CONTROL DE ACREDITACIÓN</p><h1>Control de entregas<span className="titlemark">.</span></h1><p>Todos los pedidos, talles y entregas en un solo lugar.</p></div><div className="introactions"><button className="resetbutton" disabled={loading||busy||!orders.length} onClick={()=>{setError('');setResetOpen(true);}}><RotateCcw size={17}/><span>Reiniciar entregas</span></button><button className="refresh" onClick={()=>{setLoading(true);void load();}} disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/><span>Actualizar listado</span></button></div></div>
 <section className="summary" aria-label="Resumen de entregas">
 <div className="stat"><span className="staticon"><ClipboardList size={20}/></span><div><small>Pedidos</small><strong>{orders.length||'—'}</strong></div></div>
 <div className="stat pendingstat"><span className="staticon"><Clock3 size={20}/></span><div><small>Por entregar</small><strong>{orders.length?orders.length-done.length:'—'}</strong></div></div>
 <div className="stat greenstat"><span className="staticon"><PackageCheck size={20}/></span><div><small>Entregados</small><strong>{orders.length?done.length:'—'}</strong></div></div>
 <div className="stat shirtstat"><span className="staticon"><Shirt size={20}/></span><div><small>Camisetas entregadas</small><strong>{orders.length?done.reduce((a,o)=>a+o.quantity,0):'—'}<span>/ {orders.reduce((a,o)=>a+o.quantity,0)||201}</span></strong></div></div>
 </section><div className="progressline"><span>Avance de entrega</span><div className="progress"><div style={{width:`${orders.length?done.length/orders.length*100:0}%`}}/></div><strong>{orders.length?Math.round(done.length/orders.length*100):0}%</strong></div>
 <section className="workspace"><div className="listtitle"><h2>Listado de pedidos</h2><span className="listtag">COPA 2026</span></div><div className="toolbar"><div className="search"><Search size={20}/><input aria-label="Buscar por nombre o número" placeholder="Buscar por nombre o N.º de listado…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>setQuery('')}><X size={17}/></button>}</div><span className="total">{visible.length} de {orders.length} pedidos</span></div><nav aria-label="Filtrar pedidos">{[['all','Todos',orders.length],['pending','Por entregar',orders.length-done.length],['done','Entregados',done.length],['verify','Por verificar',unverified.length]].map(([key,label,n])=><button key={key} aria-pressed={filter===key} className={filter===key?'active':''} onClick={()=>setFilter(String(key))}>{label}<span>{n}</span></button>)}</nav>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>void load()}>Reintentar</button></div>}{notice&&<div className="notice" role="status"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso"><X size={16}/></button></div>}
 <div className="tablehead"><span>PEDIDO / NOMBRE Y APELLIDO</span><span>CANT.</span><span>TALLES SOLICITADOS</span><span>VERIFICACIÓN</span><span>ENTREGA</span></div>
 {loading&&!orders.length?<div className="empty">Cargando listado…</div>:!visible.length?<div className="empty">No hay pedidos para mostrar con esta búsqueda.</div>:visible.map(o=><article key={o.id} className={'row '+(o.deliveredAt?'delivered':'')}><div className="person"><span className="number">{'#'+String(o.id).padStart(2,'0')}</span><div><strong>{o.name}</strong>{o.deliveredAt&&<small>Entregado · {new Date(o.deliveredAt).toLocaleString('es-UY',{timeZone:'America/Montevideo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small>}</div></div><div className="quantity">{o.quantity}<small>camisetas</small></div><div className="sizes">{o.sizes.split('·').map((s,i)=><span key={i}>{s.trim()}</span>)}</div><div>{o.verified?<span className="verified"><ClipboardCheck size={14}/>Verificado</span>:<button className="verify" onClick={()=>{setError('');setSelected(o);}}>Por verificar</button>}</div><div className="action">{o.deliveredAt?<><span className="done"><Check size={16}/>Entregado</span><button className="undo" aria-label={'Deshacer entrega de '+o.name} onClick={()=>{setError('');setSelected(o);}}><Undo2 size={16}/></button></>:<button className="deliver" onClick={()=>{setError('');setSelected(o);}}><Check size={16}/>Entregar</button>}</div></article>)}
 </section><footer><span>Copa Integración 2026 · Dirección Nacional de Bomberos</span><span>El N.º corresponde al orden del PDF, no al identificador del pedido.</span></footer></main>
 {selected&&<div className="overlay" onClick={()=>{if(!busy)setSelected(null)}}><section role="dialog" aria-modal="true" aria-labelledby="dialogtitle" className="modal" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Cerrar" disabled={busy} onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">PEDIDO DEL LISTADO N.º {selected.id}</p><h2 id="dialogtitle">{selected.deliveredAt?'Deshacer entrega':!selected.verified?'Verificar pedido':'Confirmar entrega'}</h2><h3>{selected.name}</h3><div className="detail"><Shirt size={25}/><strong>{selected.quantity} {selected.quantity===1?'camiseta':'camisetas'}</strong><p>{selected.sizes}</p></div><p>{selected.deliveredAt?'El pedido volverá a quedar pendiente de entrega.':!selected.verified?'En el PDF este pedido figura como PENDIENTE. Comprueba la información antes de marcarlo como verificado.':'Confirma que se entregaron todas las camisetas y que los talles coinciden con este pedido.'}</p>{error&&<div className="error" role="alert">{error}</div>}<div className="modalactions"><button disabled={busy} className="cancel" onClick={()=>setSelected(null)}>Cancelar</button><button autoFocus disabled={busy} className="confirm" onClick={()=>void save(selected,selected.deliveredAt?'undo':!selected.verified?'verify':'deliver')}>{busy?'Guardando…':selected.deliveredAt?'Deshacer entrega':!selected.verified?'Marcar verificado':'Confirmar entrega'}</button></div></section></div>}
 {resetOpen&&<div className="overlay" onClick={()=>{if(!busy)setResetOpen(false)}}><section role="dialog" aria-modal="true" aria-labelledby="resettitle" className="modal" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Cerrar" disabled={busy} onClick={()=>setResetOpen(false)}><X/></button><p className="eyebrow">REINICIAR CONTROL DE ENTREGA</p><h2 id="resettitle">¿Volver las entregas a cero?</h2><div className="detail"><RotateCcw size={25}/><strong>{done.length} {done.length===1?'pedido entregado':'pedidos entregados'}</strong><p>{done.reduce((a,o)=>a+o.quantity,0)} camisetas entregadas</p></div><p>Todos los pedidos volverán a quedar pendientes de entrega. Se borrarán las fechas y horas de entrega. Los nombres, cantidades, talles y verificaciones se conservarán.</p><p className="resetwarning">Este reinicio afecta todo el listado, incluso los pedidos que no se muestran con el filtro actual. No se puede deshacer.</p>{error&&<div className="error" role="alert">{error}</div>}<div className="modalactions"><button autoFocus disabled={busy} className="cancel" onClick={()=>setResetOpen(false)}>Cancelar</button><button disabled={busy} className="confirm resetconfirm" onClick={()=>void resetDeliveries()}>{busy?'Reiniciando…':'Sí, reiniciar a 0'}</button></div></section></div>}</>;

}
